[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sunrock-testing"
version = "0.1.0"
description = "Python code used for testing the SUNROCK chip."
readme = "README.md"
license = {file = "LICENSE"}
dependencies = []

[project.optional-dependencies]
dev = [
    "black",
    "coverage",
    "isort",
    "isort[colors]",
    "mypy",
    "pylint",
    "pytest",
    "pytest-clarity",
    "ruff",
]

[project.scripts]
labtest = "labtest.labtest:main"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
]

[tool.ruff]
lint.pydocstyle.convention = "google"
